servers:
    - https://gitlab.com
token: 1234
users:
    - username: StefanHolst
    - username: asger
    - username: alexnlarsen
    - username: dennis-ks
    - username: dragos.brezoi
    - username: jfaaborg
    - username: romadsen-ks
    - username: eneshaluk
projects:
    - id: gid://gitlab/Project/10858059
      labels:
          - text: Open
            label: opened
            order: 0
          - text: To be Discussed
            label: flow::To be Discussed
            order: 1
          - text: In Progress
            label: flow::In Progress
            order: 2
          - text: Merge Requested
            label: flow::Merge Requested
            order: 3
          - text: Closed
            label: closed
            order: 4
